name: V.4 Bug Report & Feedback
description: Report an issue/feedback for Serverless Framework v.4 Alpha/Beta release
labels: V4
body:
  - type: textarea
    id: version
    attributes:
      label: What version of Serverless Framework are you using?
      description: Output of `serverless --version`
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Issue description / feedback
      description: Describe the issue, repro steps, and important context to help us reproduce the issue and find the root cause.
    validations:
      required: true
